"""m2 domain tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-11 15:19:29.547495

"""

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_applications_project_id")),
        schema="apex",
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("base_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("secret_ref", sa.String(length=1024), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
        sa.UniqueConstraint("name", name=op.f("uq_connections_name")),
        schema="apex",
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("artifact_key", sa.String(length=1024), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("app_id", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        schema="apex",
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
        schema="apex",
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("prompt_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("parent_version_id", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("prompt_id", "version", name=op.f("uq_prompt_versions_prompt_id")),
        schema="apex",
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active_version_id", sa.String(length=32), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
        sa.UniqueConstraint("namespace", "key", name=op.f("uq_prompts_namespace")),
        schema="apex",
    )
    op.create_table(
        "environments",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("application_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=True),
        sa.Column("base_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["apex.applications.id"],
            name=op.f("fk_environments_applications_application_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environments")),
        sa.UniqueConstraint("application_id", "name", name=op.f("uq_environments_application_id")),
        schema="apex",
    )
    op.create_table(
        "host_mappings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("connection_id", sa.String(length=32), nullable=False),
        sa.Column("pattern", sa.String(length=1024), nullable=False),
        sa.Column("target", sa.String(length=1024), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["apex.connections.id"],
            name=op.f("fk_host_mappings_connections_connection_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_host_mappings")),
        schema="apex",
    )
    op.create_table(
        "environment_hosts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("environment_id", sa.String(length=32), nullable=False),
        sa.Column("hostname", sa.String(length=1024), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["apex.environments.id"],
            name=op.f("fk_environment_hosts_environments_environment_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_hosts")),
        schema="apex",
    )
    op.create_table(
        "environment_snapshots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("environment_id", sa.String(length=32), nullable=False),
        sa.Column(
            "scanned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["apex.environments.id"],
            name=op.f("fk_environment_snapshots_environments_environment_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_snapshots")),
        schema="apex",
    )
    # Circular prompts <-> prompt_versions FKs: use_alter constraints inside
    # create_table are silently skipped by Alembic, so create them explicitly.
    op.create_foreign_key(
        op.f("fk_prompt_versions_prompts_prompt_id"),
        "prompt_versions",
        "prompts",
        ["prompt_id"],
        ["id"],
        source_schema="apex",
        referent_schema="apex",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_prompts_prompt_versions_active_version_id"),
        "prompts",
        "prompt_versions",
        ["active_version_id"],
        ["id"],
        source_schema="apex",
        referent_schema="apex",
    )
    # (autogenerate noise removed: drop of the default-schema alembic_version table and
    #  consumer_scopes FK churn were schema-comparison artifacts, not real diffs)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_prompts_prompt_versions_active_version_id"),
        "prompts",
        schema="apex",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_prompt_versions_prompts_prompt_id"),
        "prompt_versions",
        schema="apex",
        type_="foreignkey",
    )
    op.drop_table("environment_snapshots", schema="apex")
    op.drop_table("environment_hosts", schema="apex")
    op.drop_table("host_mappings", schema="apex")
    op.drop_table("environments", schema="apex")
    op.drop_table("prompts", schema="apex")
    op.drop_table("prompt_versions", schema="apex")
    op.drop_table("drafts", schema="apex")
    op.drop_table("documents", schema="apex")
    op.drop_table("connections", schema="apex")
    op.drop_table("applications", schema="apex")
    # ### end Alembic commands ###
