/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["listConnections"];
        put?: never;
        /** Create Connection */
        post: operations["createConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["getConnection"];
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["deleteConnection"];
        options?: never;
        head?: never;
        /** Update Connection */
        patch: operations["updateConnection"];
        trace?: never;
    };
    "/v1/admin/connections/{connection_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Connection */
        post: operations["disableConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/connections/{connection_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Connection */
        post: operations["enableConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/connections/{connection_id}/host-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Host Mappings */
        get: operations["getHostMappings"];
        /**
         * Put Host Mappings
         * @description Replaces the FULL mapping list (PUT semantics).
         */
        put: operations["putHostMappings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/connections/{connection_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Build the adapter exactly as the resolver would and run the kind's probe.
         *
         *     Always 200: failures (bad secret_ref, unreachable backend, misconfigured
         *     options) come back inline as ok=false so the admin UI can show them.
         */
        post: operations["testConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/consumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consumers */
        get: operations["listConsumers"];
        put?: never;
        /** Create Consumer */
        post: operations["createConsumer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/consumers/{consumer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consumer */
        get: operations["getConsumer"];
        put?: never;
        post?: never;
        /** Delete Consumer */
        delete: operations["deleteConsumer"];
        options?: never;
        head?: never;
        /** Update Consumer */
        patch: operations["updateConsumer"];
        trace?: never;
    };
    "/v1/admin/consumers/{consumer_id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Consumer Key */
        post: operations["rotateConsumerKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["listApplications"];
        put?: never;
        /** Create Application */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/v1/catalog/applications/{application_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Application */
        post: operations["archiveApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/applications/{application_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Application */
        post: operations["unarchiveApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Environments */
        get: operations["listEnvironments"];
        put?: never;
        /** Create Environment */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/environments/{environment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Environment */
        get: operations["getEnvironment"];
        put?: never;
        post?: never;
        /** Delete Environment */
        delete: operations["deleteEnvironment"];
        options?: never;
        head?: never;
        /** Update Environment */
        patch: operations["updateEnvironment"];
        trace?: never;
    };
    "/v1/context/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Context Evidence */
        get: operations["listContextEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/context/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Context Summary */
        post: operations["createContextSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["listDocuments"];
        put?: never;
        /** Upload Document */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["listDrafts"];
        put?: never;
        /** Create Draft */
        post: operations["createDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["getDraft"];
        /** Update Draft */
        put: operations["updateDraft"];
        post?: never;
        /** Delete Draft */
        delete: operations["deleteDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pipelines */
        get: operations["listPipelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipelines/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline */
        get: operations["getPipeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipelines/{thread_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort Pipeline
         * @description Cancel the thread's active run(s) via the loopback API (engine abort lands M3).
         */
        post: operations["abortPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipelines/{thread_id}/gates/{interrupt_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Gate
         * @description Compare-and-set resume: 409 gate_superseded when the interrupt is stale.
         */
        post: operations["resumeGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompts */
        get: operations["listPrompts"];
        put?: never;
        /** Create Prompt */
        post: operations["createPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt */
        get: operations["getPrompt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Prompt */
        post: operations["archivePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback Prompt */
        post: operations["rollbackPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Prompt
         * @description Run the prompt on the `playground` assistant as a stateless background run.
         *
         *     Content precedence: explicit body.content -> body.version_id -> active version.
         *     Responds 202 with the run/thread ids; results are fetched via the LangGraph API.
         */
        post: operations["testPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Prompt */
        post: operations["unarchivePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompt Versions */
        get: operations["listPromptVersions"];
        put?: never;
        /** Save Prompt Version */
        post: operations["savePromptVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt Version */
        get: operations["getPromptVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Info */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbortPipelineResponse */
        AbortPipelineResponse: {
            /** Cancelled Run Ids */
            cancelled_run_ids: string[];
        };
        /** ActiveVersionRef */
        ActiveVersionRef: {
            /** Id */
            id: string;
            /** Version */
            version: number;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ApplicationUpdate */
        ApplicationUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /** Base Url */
            base_url?: string | null;
            kind: components["schemas"]["PortKind"];
            /** Name */
            name: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id?: string | null;
            /** Provider */
            provider: string;
            /** Secret Ref */
            secret_ref?: string | null;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /** Base Url */
            base_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            kind: components["schemas"]["PortKind"];
            /** Name */
            name: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: string | null;
            /** Provider */
            provider: string;
            /** Secret Ref */
            secret_ref: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConnectionUpdate
         * @description `kind` is immutable — create a new connection to change port kinds.
         */
        ConnectionUpdate: {
            /** Base Url */
            base_url?: string | null;
            /** Name */
            name?: string | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
            /** Project Id */
            project_id?: string | null;
            /** Provider */
            provider?: string | null;
            /** Secret Ref */
            secret_ref?: string | null;
        };
        /** ConsumerCreateRequest */
        ConsumerCreateRequest: {
            consumer_type: components["schemas"]["ConsumerType"];
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Scopes */
            scopes?: components["schemas"]["ScopeRef"][];
        };
        /** ConsumerCreated */
        ConsumerCreated: {
            /**
             * Api Key
             * @description The raw API key. Shown exactly once — it is stored only as a sha256 hash and can never be retrieved again.
             */
            api_key: string;
            consumer_type: components["schemas"]["ConsumerType"];
            /** Created At */
            created_at: string | null;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /**
             * Key Fingerprint
             * @description First 8 hex chars of the stored sha256 key hash (NOT of the raw key, which is never persisted). Stable identifier for a credential.
             */
            key_fingerprint: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Scopes */
            scopes: components["schemas"]["ScopeRef"][];
        };
        /** ConsumerInfo */
        ConsumerInfo: {
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Scopes */
            scopes: components["schemas"]["ScopeRef"][];
        };
        /** ConsumerRead */
        ConsumerRead: {
            consumer_type: components["schemas"]["ConsumerType"];
            /** Created At */
            created_at: string | null;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /**
             * Key Fingerprint
             * @description First 8 hex chars of the stored sha256 key hash (NOT of the raw key, which is never persisted). Stable identifier for a credential.
             */
            key_fingerprint: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Scopes */
            scopes: components["schemas"]["ScopeRef"][];
        };
        /**
         * ConsumerType
         * @enum {string}
         */
        ConsumerType: "dashboard" | "headless" | "internal";
        /**
         * ConsumerUpdateRequest
         * @description Partial update; omitted fields are left unchanged.
         */
        ConsumerUpdateRequest: {
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
            role?: components["schemas"]["Role"] | null;
            /** Scopes */
            scopes?: components["schemas"]["ScopeRef"][] | null;
        };
        /** ContextSummaryAccepted */
        ContextSummaryAccepted: {
            /** Run Id */
            run_id: string;
            /**
             * Stream Url
             * @description Join the run's SSE stream: GET this path on the LangGraph surface (same host) with your API key.
             */
            stream_url: string;
        };
        /** ContextSummaryRequest */
        ContextSummaryRequest: {
            /** Document Ids */
            document_ids?: string[];
            /** Project Id */
            project_id?: string | null;
            /** Subject */
            subject: string;
            /** Work Item Keys */
            work_item_keys?: string[];
        };
        /** CreatePromptRequest */
        CreatePromptRequest: {
            /** Content */
            content: string;
            /** Description */
            description?: string | null;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Note */
            note?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /** App Id */
            app_id?: string | null;
            /** Artifact Key */
            artifact_key: string;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Project Id */
            project_id?: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Summary */
            summary?: string | null;
            /** Uploaded By */
            uploaded_by?: string | null;
        };
        /** DraftCreateRequest */
        DraftCreateRequest: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id?: string | null;
            /** Title */
            title: string;
        };
        /** DraftRead */
        DraftRead: {
            /** Created At */
            created_at: string | null;
            /** Created By */
            created_by: string | null;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id: string | null;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DraftUpdateRequest
         * @description Full replace of the editable fields (title + payload); project_id is fixed.
         */
        DraftUpdateRequest: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Title */
            title: string;
        };
        /** EnvironmentCreate */
        EnvironmentCreate: {
            /** Application Id */
            application_id: string;
            /** Base Url */
            base_url?: string | null;
            /** Hosts */
            hosts?: components["schemas"]["HostIn"][];
            /** Kind */
            kind?: string | null;
            /** Name */
            name: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** EnvironmentOut */
        EnvironmentOut: {
            /** Application Id */
            application_id: string;
            /** Base Url */
            base_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Hosts */
            hosts: components["schemas"]["HostOut"][];
            /** Id */
            id: string;
            /** Kind */
            kind: string | null;
            last_snapshot?: components["schemas"]["SnapshotSummary"] | null;
            /** Name */
            name: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EnvironmentUpdate */
        EnvironmentUpdate: {
            /** Base Url */
            base_url?: string | null;
            /** Hosts */
            hosts?: components["schemas"]["HostIn"][] | null;
            /** Kind */
            kind?: string | null;
            /** Name */
            name?: string | null;
            /** Options */
            options?: {
                [key: string]: unknown;
            } | null;
        };
        /** EvidencePacket */
        EvidencePacket: {
            /** Id */
            id: string | null;
            /** Ref */
            ref: string | null;
            /** Source */
            source: string;
            /** Summary */
            summary: string | null;
            /** Thread Id */
            thread_id: string | null;
            /** Title */
            title: string;
        };
        /** GateInterrupt */
        GateInterrupt: {
            /** Interrupt Id */
            interrupt_id?: string | null;
            /** Kind */
            kind?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Phase */
            phase?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostIn */
        HostIn: {
            /** Hostname */
            hostname: string;
            /** Role */
            role?: string | null;
        };
        /** HostMappingIn */
        HostMappingIn: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Pattern */
            pattern: string;
            /** Target */
            target: string;
        };
        /** HostMappingOut */
        HostMappingOut: {
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Pattern */
            pattern: string;
            /** Target */
            target: string;
        };
        /** HostOut */
        HostOut: {
            /** Hostname */
            hostname: string;
            /** Id */
            id: string;
            /** Role */
            role: string | null;
        };
        /** PendingGate */
        PendingGate: {
            /** Interrupt Id */
            interrupt_id?: string | null;
            /** Kind */
            kind?: string | null;
            /** Phase */
            phase?: string | null;
        };
        /** PhaseStripEntry */
        PhaseStripEntry: {
            /** Attempt */
            attempt?: number | null;
            /** Phase */
            phase: string;
            /** Status */
            status: string;
        };
        /** PipelineDetail */
        PipelineDetail: {
            /** App Id */
            app_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Current Phase */
            current_phase?: string | null;
            /** Interrupts */
            interrupts?: components["schemas"]["GateInterrupt"][];
            pending_gate?: components["schemas"]["PendingGate"] | null;
            /** Phase Strip */
            phase_strip: components["schemas"]["PhaseStripEntry"][];
            /** Project Id */
            project_id?: string | null;
            /** Thread Id */
            thread_id: string;
            /** Thread Status */
            thread_status?: string | null;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Values */
            values?: {
                [key: string]: unknown;
            };
        };
        /** PipelineListResponse */
        PipelineListResponse: {
            /** Items */
            items: components["schemas"]["PipelineSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PipelineSummary */
        PipelineSummary: {
            /** App Id */
            app_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Current Phase */
            current_phase?: string | null;
            pending_gate?: components["schemas"]["PendingGate"] | null;
            /** Phase Strip */
            phase_strip: components["schemas"]["PhaseStripEntry"][];
            /** Project Id */
            project_id?: string | null;
            /** Thread Id */
            thread_id: string;
            /** Thread Status */
            thread_status?: string | null;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * PortKind
         * @enum {string}
         */
        PortKind: "work_tracking" | "log_search" | "observability" | "documents" | "cluster_inventory" | "source_control" | "execution_engine" | "artifact_store" | "secrets";
        /** ProbeResult */
        ProbeResult: {
            /** Detail */
            detail: string;
            /** Latency Ms */
            latency_ms: number;
            /** Ok */
            ok: boolean;
        };
        /** PromptDetail */
        PromptDetail: {
            active_version?: components["schemas"]["ActiveVersionRef"] | null;
            /** Archived At */
            archived_at?: string | null;
            /** Content */
            content?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Note */
            note?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** PromptSummary */
        PromptSummary: {
            active_version?: components["schemas"]["ActiveVersionRef"] | null;
            /** Archived At */
            archived_at?: string | null;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** PromptVersionDetail */
        PromptVersionDetail: {
            /** Content */
            content: string;
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /** Version */
            version: number;
        };
        /** PromptVersionInfo */
        PromptVersionInfo: {
            /** Created At */
            created_at?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /** Version */
            version: number;
        };
        /** ResumeGateRequest */
        ResumeGateRequest: {
            /** Action */
            action: string;
            /** Instructions */
            instructions?: string | null;
            /** Message */
            message?: string | null;
            /** Note */
            note?: string | null;
            /** Prompt */
            prompt?: {
                [key: string]: unknown;
            } | null;
        };
        /** ResumeGateResponse */
        ResumeGateResponse: {
            /** Run Id */
            run_id: string;
        };
        /**
         * Role
         * @description Ordered roles: viewer < operator < admin.
         * @enum {string}
         */
        Role: "viewer" | "operator" | "admin";
        /** RollbackRequest */
        RollbackRequest: {
            /** Version Id */
            version_id: string;
        };
        /** SaveVersionRequest */
        SaveVersionRequest: {
            /** Content */
            content: string;
            /** Note */
            note?: string | null;
        };
        /**
         * ScopeRef
         * @description A project (optionally narrowed to one app) the consumer may act on.
         */
        ScopeRef: {
            /** App Id */
            app_id?: string | null;
            /** Project Id */
            project_id: string;
        };
        /**
         * SnapshotSummary
         * @description Latest cluster-inventory scan, summarized (full data stays server-side).
         */
        SnapshotSummary: {
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Service Count */
            service_count: number;
        };
        /** SystemInfo */
        SystemInfo: {
            consumer: components["schemas"]["ConsumerInfo"];
            /** Environment */
            environment: string;
            /** Features */
            features: {
                [key: string]: boolean;
            };
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** TestPromptRequest */
        TestPromptRequest: {
            /** Content */
            content?: string | null;
            /** Sample Input */
            sample_input?: {
                [key: string]: unknown;
            } | null;
            /** Version Id */
            version_id?: string | null;
        };
        /** TestPromptResponse */
        TestPromptResponse: {
            /** Run Id */
            run_id: string;
            /** Thread Id */
            thread_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listConnections: {
        parameters: {
            query?: {
                kind?: components["schemas"]["PortKind"] | null;
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disableConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enableConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHostMappings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostMappingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    putHostMappings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostMappingIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostMappingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    testConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listConsumers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumerRead"][];
                };
            };
        };
    };
    createConsumer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumerCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getConsumer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer id */
                consumer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteConsumer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer id */
                consumer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateConsumer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer id */
                consumer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumerUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotateConsumerKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Consumer id */
                consumer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumerCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listApplications: {
        parameters: {
            query?: {
                project?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archiveApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchiveApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: {
                application?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listContextEvidence: {
        parameters: {
            query?: {
                /** @description Filter to one project */
                project?: string | null;
                /** @description Narrow to one thread */
                thread_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePacket"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createContextSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextSummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextSummaryAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                project?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    app_id?: string;
                    /** Format: binary */
                    file: string;
                    project_id?: string;
                    summary?: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDrafts: {
        parameters: {
            query?: {
                /** @description Filter to one project */
                project?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft id */
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft id */
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Draft id */
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPipelines: {
        parameters: {
            query?: {
                project?: string | null;
                status?: ("idle" | "busy" | "interrupted" | "error") | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abortPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbortPipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumeGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                interrupt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeGateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeGateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPrompts: {
        parameters: {
            query?: {
                namespace?: string | null;
                include_archived?: boolean;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archivePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollbackPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    testPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestPromptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPromptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchivePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPromptVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    savePromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
}
